[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"
always_use_create_2_factory = true
create2_deployer = "0x4e59b44847b379578588920ca78fbf26c0b4956c"

memory_limit = 1342177280
optimizer_runs = 600
# dynamic_test_linking = true
# Auto-detect Solidity versions from pragma statements
auto_detect_solc = true
ffi = true 

fs_permissions = [
    { access = "read", path = "./out"},
    { access = "read-write", path = "../frontend/public/powered/" }
]

# Remappings for dependencies
# NOTE: Order matters! More specific remappings should come first
remappings = [
    # Your project's remappings (@ prefixed - these take priority)
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@forge-std/=lib/forge-std/src/",
    "@solady/=lib/solady/src/",
    "@solbase/=lib/solbase/src/",
    "@safe/=lib/safe-smart-account/contracts/",
    "@chainlink/contracts/=lib/chainlink-evm/contracts", 
    "@chainlink/contracts-ccip/=lib/chainlink-ccip/chains/evm/contracts",
    "@mocks/=test/mocks/", 
    "@src/=src/",
    "@script/=script"
    
] 

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "attributes_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = false

[fuzz]
runs = 256
depth = 256
fail_on_revert = true 
seed = '0x4ea'

[invariant] 
runs = 32
depth = 32 
fail_on_revert = true 

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
